Astronomy:
  name: projectprogramming
  version: 1.0

source:
  git_rev: 1.0
  git_url: https://github.com/AstroAndy86/projectprogramming

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - astropy >=1.2.1
    - scipy
    - wxpython


test:
  imports:
    - projectprogramming

about:
  home: https://github.com/AstroAndy86/projectprogramming
  license: GPL3
  license_file: LICENSE
  description: 'Computes cool stuff' 